; Game
STATE_MARK_3_LOGO_BIT  = 0
STATE_START_SCREEN_BIT = 1
STATE_DEMO_BIT         = 2
STATE_GAMEPLAY_BIT     = 3
STATE_PAUSED_BIT       = 4

STATE_MARK_3_LOGO  = 1 << STATE_MARK_3_LOGO_BIT
STATE_START_SCREEN = 1 << STATE_START_SCREEN_BIT
STATE_DEMO         = 1 << STATE_DEMO_BIT
STATE_GAMEPLAY     = 1 << STATE_GAMEPLAY_BIT
STATE_PAUSED       = 1 << STATE_PAUSED_BIT

INITIAL_LIVES = $02

MARK_3_LOGO_TIMER = $A0

; Entities
ENTITY_ARRAY_SIZE = $1B
ENTITY_SIZE = $20


ENTITY_BOMB         = $04
ENTITY_ENEMY_BULLET = $07
ENTITY_DRAGONFLY    = $0A
ENTITY_DROP_STAR    = $0F
ENTITY_JELLYFISH    = $15
ENTITY_STAR         = $16
ENTITY_ENEMY_2      = $17
ENTITY_EXTRA_LIFE   = $22


; Entity config
ENTITY_ENEMY_1_X_POS           = $08
ENTITY_ENEMY_1_X_VELOCITY      = $02
ENTITY_ENEMY_1_Y_POS           = $F8
ENTITY_ENEMY_1_Y_VEL           = $02
ENTITY_ENEMY_1_STATE1_TIMER    = $48
ENTITY_ENEMY_1_ANIMATION_TIMER = $0C

ENTITY_BOMB_DRAG               = $10

; Input
JOY_UP_BIT    = 0
JOY_DOWN_BIT  = 1
JOY_LEFT_BIT  = 2
JOY_RIGHT_BIT = 3
JOY_BTN1_BIT  = 4
JOY_BTN2_BIT  = 5

JOY_UP    = 1 << JOY_UP_BIT
JOY_DOWN  = 1 << JOY_DOWN_BIT
JOY_LEFT  = 1 << JOY_LEFT_BIT
JOY_RIGHT = 1 << JOY_RIGHT_BIT
JOY_FIREA = 1 << JOY_BTN1_BIT
JOY_FIREB = 1 << JOY_BTN2_BIT