; Game
STATE_MARK_3_LOGO  = $01
STATE_START_SCREEN = $02
STATE_DEMO         = $04
STATE_GAMEPLAY     = $08
STATE_PAUSED       = $10

INITIAL_LIVES = $02

MARK_3_LOGO_TIMER = $A0

; Entities
ENTITY_ARRAY_SIZE = $1B
ENTITY_SIZE = $20


ENTITY_BOMB     = $04
ENTITY_ENEMY_1  = $0A
ENTITY_JELLYFISH     = $16
ENTITY_STAR     = $16
ENTITY_ENEMY_2  = $17


; Entity config
ENTITY_ENEMY_1_X_POS           = $08
ENTITY_ENEMY_1_X_VELOCITY      = $02
ENTITY_ENEMY_1_Y_POS           = $F8
ENTITY_ENEMY_1_Y_VEL           = $02
ENTITY_ENEMY_1_STATE1_TIMER    = $48
ENTITY_ENEMY_1_ANIMATION_TIMER = $0C

ENTITY_BOMB_DRAG               = $10

; Input
JOY_UP_BIT    = 0
JOY_DOWN_BIT  = 1
JOY_LEFT_BIT  = 2
JOY_RIGHT_BIT = 3
JOY_BTN1_BIT  = 4
JOY_BTN2_BIT  = 5

JOY_UP    = 1 << JOY_UP_BIT
JOY_DOWN  = 1 << JOY_DOWN_BIT
JOY_LEFT  = 1 << JOY_LEFT_BIT
JOY_RIGHT = 1 << JOY_RIGHT_BIT
JOY_FIREA = 1 << JOY_BTN1_BIT
JOY_FIREB = 1 << JOY_BTN2_BIT