entityUpdatersPointers:
.dw updatePlayer1
.dw updatePlayer2
.dw updateBullet
.dw updateBomb
.dw updateEntity05
.dw updateEntity06
.dw updateEntity07
.dw updateExplosion
.dw updateEntity09
.dw updateEnemy1
.dw updateEntity0B
.dw updateEntity0C
.dw updateEntity0D
.dw updateEntity0E
.dw updateEntity0F
.dw updateEntity10
.dw updateEntity11
.dw updateEntity12
.dw updateEntity13
.dw updateEntity14
.dw updateJellyfish
.dw updateStar
.dw updateEnemy2
.dw updateEntity18
.dw updateEntity19
.dw updateEntity1A
.dw updateEntity1B
.dw updateEntity1C
.dw updateEntity1D
.dw updateEntity1E
.dw updateEntity1F
.dw updateEntity20
.dw updateEntity21
.dw updateEntity22
